# Generated by Django 3.2.5 on 2021-08-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imagen',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imagen',
            name='image',
            field=models.ImageField(blank=True, default='media/L0Wwka.png', upload_to='media'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
